app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting